github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
ports:
  - port: 4200
    visibility: public
tasks:
  - init: npm install
    command: npm start
vscode:
  extensions:
    - angular.ng-template
    - eamodio.gitlens
    - nrwl.angular-console
    - esbenp.prettier-vscode
    - github.vscode-pull-request-github
    - dbaeumer.vscode-eslint
    - firsttris.vscode-jest-runner
